[global]
developmentMode = false

[server]
runOnSave = false
allowRunOnSave = false
maxUploadSize = 10
maxMessageSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
caching = true
displayEnabled = true
showErrorDetails = false 